---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- route.yaml

patches:

- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rest-fights
    spec:
      template:
        spec:
          containers:
            - name: rest-fights
              image: image-registry.openshift-image-registry.svc:5000/quarkus-superheroes-user1/rest-fights:2024-10-29-18-27-35
