---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- route.yaml

patches:

- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rest-fights
    spec:
      template:
        spec:
          containers:
            - name: rest-fights
              image: rest-fights:latest
